-- LINE schema for Supabase Postgres.
--
-- Every table is reached only through the Next.js server, which connects as the
-- database owner. Row level security is on for every table and there are no policies,
-- so the anon and authenticated roles (the publishable key, a signed-in browser) get nothing.
--
-- Table names are unqualified on purpose: the migration runner sets search_path,
-- which lets the core-rule test apply the same file to a throwaway schema.

create table profiles (
  id integer generated by default as identity primary key,
  -- Supabase Auth account. Null only for people created by the core-rule test.
  auth_id uuid unique references auth.users (id) on delete cascade,
  username text not null unique check (username = lower(username) and length(username) between 2 and 30),
  display_name text not null,
  bio text not null default '',
  avatar_color text not null,
  initials text not null,
  role text not null default 'user',
  who_can_share text not null default 'friends',
  who_can_add text not null default 'everyone',
  who_can_reshare text not null default 'recipients',
  location text not null default '',
  work text not null default '',
  education text not null default '',
  restricted smallint not null default 0,
  suspended smallint not null default 0,
  created_at timestamptz not null default now()
);

create table permissions (
  user_id integer not null references profiles (id) on delete cascade,
  permission text not null,
  primary key (user_id, permission)
);

create table friendships (
  id integer generated by default as identity primary key,
  requester_id integer not null references profiles (id) on delete cascade,
  addressee_id integer not null references profiles (id) on delete cascade,
  status text not null check (status in ('pending', 'accepted')),
  created_at timestamptz not null default now(),
  unique (requester_id, addressee_id)
);

create table blocks (
  blocker_id integer not null references profiles (id) on delete cascade,
  blocked_id integer not null references profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id)
);

create table friend_groups (
  id integer generated by default as identity primary key,
  owner_id integer not null references profiles (id) on delete cascade,
  name text not null,
  allows_inbound_share smallint not null default 1,
  created_at timestamptz not null default now()
);

create table friend_group_members (
  group_id integer not null references friend_groups (id) on delete cascade,
  user_id integer not null references profiles (id) on delete cascade,
  primary key (group_id, user_id)
);

create table friend_lists (
  id integer generated by default as identity primary key,
  owner_id integer not null references profiles (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table friend_list_members (
  list_id integer not null references friend_lists (id) on delete cascade,
  user_id integer not null references profiles (id) on delete cascade,
  primary key (list_id, user_id)
);

create table share_allow (
  user_id integer not null references profiles (id) on delete cascade,
  allowed_id integer not null references profiles (id) on delete cascade,
  primary key (user_id, allowed_id)
);

create table posts (
  id integer generated by default as identity primary key,
  author_id integer not null references profiles (id) on delete cascade,
  kind text not null check (kind in ('text', 'photo', 'video', 'short', 'long_video', 'reel')),
  body text not null,
  -- Uploaded files: [{ "path": "u/<profile id>/<uuid>.jpg", "mime": "image/jpeg" }] in the private line-media bucket.
  frames jsonb not null default '[]'::jsonb,
  allow_reshare smallint not null default 1,
  hidden smallint not null default 0,
  hidden_reason text,
  seed_key text unique,
  created_at timestamptz not null default now()
);

create table shares (
  id integer generated by default as identity primary key,
  post_id integer not null references posts (id) on delete cascade,
  from_user_id integer not null references profiles (id) on delete cascade,
  to_user_id integer not null references profiles (id) on delete cascade,
  share_kind text not null,
  group_id integer references friend_groups (id) on delete set null,
  list_id integer references friend_lists (id) on delete set null,
  parent_share_id integer references shares (id) on delete set null,
  note text,
  created_at timestamptz not null default now(),
  unique (post_id, from_user_id, to_user_id)
);

create table notifications (
  id integer generated by default as identity primary key,
  user_id integer not null references profiles (id) on delete cascade,
  kind text not null,
  actor_id integer not null references profiles (id) on delete cascade,
  post_id integer references posts (id) on delete cascade,
  share_id integer references shares (id) on delete cascade,
  read smallint not null default 0,
  created_at timestamptz not null default now()
);

create table reports (
  id integer generated by default as identity primary key,
  reporter_id integer not null references profiles (id) on delete cascade,
  target_type text not null,
  target_id integer not null,
  category text not null,
  details text not null default '',
  status text not null default 'open',
  queue text not null default 'moderator',
  resolution text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table tickets (
  id integer generated by default as identity primary key,
  user_id integer not null references profiles (id) on delete cascade,
  subject text not null,
  body text not null,
  status text not null default 'open',
  assignee_id integer references profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

-- Append-only. No foreign key on staff_id so history outlives the account.
create table audit_log (
  id integer generated by default as identity primary key,
  staff_id integer not null,
  staff_role text not null,
  action text not null,
  target_type text,
  target_id integer,
  reason text not null,
  previous_state text,
  new_state text,
  case_id integer,
  created_at timestamptz not null default now()
);

create table settings (
  key text primary key,
  value text not null
);

create table reactions (
  user_id integer not null references profiles (id) on delete cascade,
  post_id integer not null references posts (id) on delete cascade,
  kind text not null default 'like',
  created_at timestamptz not null default now(),
  primary key (user_id, post_id, kind)
);

create table comments (
  id integer generated by default as identity primary key,
  post_id integer not null references posts (id) on delete cascade,
  author_id integer not null references profiles (id) on delete cascade,
  parent_id integer references comments (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create index idx_posts_author on posts (author_id, created_at desc);
create index idx_posts_kind on posts (kind, created_at desc);
create index idx_comments_post on comments (post_id, created_at);
create index idx_shares_to on shares (to_user_id, created_at desc);
create index idx_shares_post on shares (post_id, to_user_id);
create index idx_shares_from on shares (from_user_id, to_user_id);
create index idx_reactions_post on reactions (post_id, kind);
create index idx_notifications_user on notifications (user_id, read, created_at desc);
create index idx_reports_queue on reports (queue, status);
create index idx_friendships_addressee on friendships (addressee_id, status);
create index idx_blocks_blocked on blocks (blocked_id);

-- Audit history cannot be changed or erased by row operations.
create function line_audit_log_immutable() returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'audit history cannot be erased';
  end if;
  raise exception 'audit history cannot be altered';
end;
$$;

create trigger audit_log_no_change
before update or delete on audit_log
for each row execute function line_audit_log_immutable();

revoke all on function line_audit_log_immutable() from public;

-- Lock every LINE table: RLS on, no policies, no grants for client roles.
do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles', 'permissions', 'friendships', 'blocks', 'friend_groups', 'friend_group_members',
    'friend_lists', 'friend_list_members', 'share_allow', 'posts', 'shares', 'notifications',
    'reports', 'tickets', 'audit_log', 'settings', 'reactions', 'comments'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('revoke all on table %I from anon, authenticated', t);
  end loop;
end;
$$;

do $$
declare
  s record;
begin
  for s in
    select c.relname from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where c.relkind = 'S' and n.nspname = current_schema()
  loop
    execute format('revoke all on sequence %I from anon, authenticated', s.relname);
  end loop;
end;
$$;
-- Private bucket for uploaded photos, videos and reels.
-- No storage policies are added, so browsers cannot read or list it with the publishable key.
-- The server checks access first, then hands out a short-lived signed URL.
-- Uploads use one-time signed upload URLs that the server issues to the signed-in author.
do $$
begin
  if to_regclass('storage.buckets') is not null then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values (
      'line-media',
      'line-media',
      false,
      52428800,
      array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm', 'video/quicktime']
    )
    on conflict (id) do update
      set public = false,
          file_size_limit = excluded.file_size_limit,
          allowed_mime_types = excluded.allowed_mime_types;
  end if;
end;
$$;

-- ── 20261010000000_follows_avatars.sql ──
-- LINE update 2026-10-10: follows, a Followers audience, profile and cover photos.
-- Additive and safe to run more than once.

alter table profiles add column if not exists avatar_path text;
alter table profiles add column if not exists cover_path text;

-- Anyone can follow anyone (no approval). Following never allows direct sharing.
create table if not exists follows (
  follower_id integer not null references profiles (id) on delete cascade,
  followee_id integer not null references profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followee_id),
  check (follower_id <> followee_id)
);
create index if not exists idx_follows_followee on follows (followee_id, created_at desc);

-- A post sent to "Followers" by from_user_id: visible to everyone who follows that person,
-- including people who follow later.
create table if not exists follower_shares (
  post_id integer not null references posts (id) on delete cascade,
  from_user_id integer not null references profiles (id) on delete cascade,
  note text,
  created_at timestamptz not null default now(),
  primary key (post_id, from_user_id)
);
create index if not exists idx_follower_shares_from on follower_shares (from_user_id, created_at desc);

alter table follows enable row level security;
alter table follower_shares enable row level security;
revoke all on table follows from anon, authenticated;
revoke all on table follower_shares from anon, authenticated;

-- Public bucket for profile and cover photos (public profile info). Post media stays in the private line-media bucket.
do $$
begin
  if to_regclass('storage.buckets') is not null then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values ('line-profiles', 'line-profiles', true, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
    on conflict (id) do update
      set public = true,
          file_size_limit = excluded.file_size_limit,
          allowed_mime_types = excluded.allowed_mime_types;
  end if;
end;
$$;

-- ── 20261010010000_hidden.sql ──
-- LINE update 2026-10-10 (b): private Dislike and "Hide all posts from <name>".
-- Additive and safe to run more than once. Never shown publicly; nobody is notified.

create table if not exists hidden_posts (
  user_id integer not null references profiles (id) on delete cascade,
  post_id integer not null references posts (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

create table if not exists hidden_authors (
  user_id integer not null references profiles (id) on delete cascade,
  author_id integer not null references profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, author_id),
  check (user_id <> author_id)
);

alter table hidden_posts enable row level security;
alter table hidden_authors enable row level security;
revoke all on table hidden_posts from anon, authenticated;
revoke all on table hidden_authors from anon, authenticated;

-- ── 20261010020000_tab_bar.sql ──
-- LINE update 2026-10-10 (c): per-user bottom tab bar. Additive and safe to run more than once.
-- Comma-separated tab keys, e.g. 'home,discover,reels,profile'. Null means the default bar.
alter table profiles add column if not exists tab_bar text;

-- LINE update 2026-10-10 (d): real groups with their own feed and members-only comment threads.
-- Additive and safe to run more than once.

create table if not exists line_groups (
  id integer generated by default as identity primary key,
  name text not null,
  about text not null default '',
  photo_path text,
  created_by integer references profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists line_group_members (
  group_id integer not null references line_groups (id) on delete cascade,
  user_id integer not null references profiles (id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  joined_at timestamptz not null default now(),
  muted smallint not null default 0,
  primary key (group_id, user_id)
);

-- A post shared into a group. Members who joined before this row was created can see the post.
create table if not exists group_posts (
  id integer generated by default as identity primary key,
  group_id integer not null references line_groups (id) on delete cascade,
  post_id integer not null references posts (id) on delete cascade,
  shared_by integer not null references profiles (id) on delete cascade,
  note text,
  created_at timestamptz not null default now(),
  unique (group_id, post_id)
);

-- Comments with a group_id belong to that group's private thread on the post.
alter table comments add column if not exists group_id integer references line_groups (id) on delete cascade;
alter table notifications add column if not exists group_id integer references line_groups (id) on delete cascade;

create index if not exists idx_group_members_user on line_group_members (user_id);
create index if not exists idx_group_posts_group on group_posts (group_id, created_at desc);
create index if not exists idx_group_posts_post on group_posts (post_id);
create index if not exists idx_comments_group on comments (post_id, group_id);

alter table line_groups enable row level security;
alter table line_group_members enable row level security;
alter table group_posts enable row level security;
revoke all on table line_groups from anon, authenticated;
revoke all on table line_group_members from anon, authenticated;
revoke all on table group_posts from anon, authenticated;
