-- LINE schema updates for an existing database. Paste each new section into the Supabase SQL Editor once, in order.
-- Every section is idempotent (safe to re-run). Fresh installs use supabase/schema.sql instead.

-- ═══ 2026-10-10: follows, Followers audience, profile & cover photos (supabase/migrations/20261010000000_follows_avatars.sql) ═══
-- LINE update 2026-10-10: follows, a Followers audience, profile and cover photos.
-- Additive and safe to run more than once.

alter table profiles add column if not exists avatar_path text;
alter table profiles add column if not exists cover_path text;

-- Anyone can follow anyone (no approval). Following never allows direct sharing.
create table if not exists follows (
  follower_id integer not null references profiles (id) on delete cascade,
  followee_id integer not null references profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followee_id),
  check (follower_id <> followee_id)
);
create index if not exists idx_follows_followee on follows (followee_id, created_at desc);

-- A post sent to "Followers" by from_user_id: visible to everyone who follows that person,
-- including people who follow later.
create table if not exists follower_shares (
  post_id integer not null references posts (id) on delete cascade,
  from_user_id integer not null references profiles (id) on delete cascade,
  note text,
  created_at timestamptz not null default now(),
  primary key (post_id, from_user_id)
);
create index if not exists idx_follower_shares_from on follower_shares (from_user_id, created_at desc);

alter table follows enable row level security;
alter table follower_shares enable row level security;
revoke all on table follows from anon, authenticated;
revoke all on table follower_shares from anon, authenticated;

-- Public bucket for profile and cover photos (public profile info). Post media stays in the private line-media bucket.
do $$
begin
  if to_regclass('storage.buckets') is not null then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values ('line-profiles', 'line-profiles', true, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
    on conflict (id) do update
      set public = true,
          file_size_limit = excluded.file_size_limit,
          allowed_mime_types = excluded.allowed_mime_types;
  end if;
end;
$$;

-- ═══ 2026-10-10 (b): Dislike and hidden people (supabase/migrations/20261010010000_hidden.sql) ═══
-- LINE update 2026-10-10 (b): private Dislike and "Hide all posts from <name>".
-- Additive and safe to run more than once. Never shown publicly; nobody is notified.

create table if not exists hidden_posts (
  user_id integer not null references profiles (id) on delete cascade,
  post_id integer not null references posts (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

create table if not exists hidden_authors (
  user_id integer not null references profiles (id) on delete cascade,
  author_id integer not null references profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, author_id),
  check (user_id <> author_id)
);

alter table hidden_posts enable row level security;
alter table hidden_authors enable row level security;
revoke all on table hidden_posts from anon, authenticated;
revoke all on table hidden_authors from anon, authenticated;

-- ═══ 2026-10-10 (c): tab bar (supabase/migrations/20261010020000_tab_bar.sql) ═══
-- LINE update 2026-10-10 (c): per-user bottom tab bar. Additive and safe to run more than once.
-- Comma-separated tab keys, e.g. 'home,discover,reels,profile'. Null means the default bar.
alter table profiles add column if not exists tab_bar text;

-- LINE update 2026-10-10 (d): real groups with their own feed and members-only comment threads.
-- Additive and safe to run more than once.

create table if not exists line_groups (
  id integer generated by default as identity primary key,
  name text not null,
  about text not null default '',
  photo_path text,
  created_by integer references profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists line_group_members (
  group_id integer not null references line_groups (id) on delete cascade,
  user_id integer not null references profiles (id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  joined_at timestamptz not null default now(),
  muted smallint not null default 0,
  primary key (group_id, user_id)
);

-- A post shared into a group. Members who joined before this row was created can see the post.
create table if not exists group_posts (
  id integer generated by default as identity primary key,
  group_id integer not null references line_groups (id) on delete cascade,
  post_id integer not null references posts (id) on delete cascade,
  shared_by integer not null references profiles (id) on delete cascade,
  note text,
  created_at timestamptz not null default now(),
  unique (group_id, post_id)
);

-- Comments with a group_id belong to that group's private thread on the post.
alter table comments add column if not exists group_id integer references line_groups (id) on delete cascade;
alter table notifications add column if not exists group_id integer references line_groups (id) on delete cascade;

create index if not exists idx_group_members_user on line_group_members (user_id);
create index if not exists idx_group_posts_group on group_posts (group_id, created_at desc);
create index if not exists idx_group_posts_post on group_posts (post_id);
create index if not exists idx_comments_group on comments (post_id, group_id);

alter table line_groups enable row level security;
alter table line_group_members enable row level security;
alter table group_posts enable row level security;
revoke all on table line_groups from anon, authenticated;
revoke all on table line_group_members from anon, authenticated;
revoke all on table group_posts from anon, authenticated;
