-- LINE update 2026-10-10 (d): real groups with their own feed and members-only comment threads.
-- Additive and safe to run more than once.

create table if not exists line_groups (
  id integer generated by default as identity primary key,
  name text not null,
  about text not null default '',
  photo_path text,
  created_by integer references profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists line_group_members (
  group_id integer not null references line_groups (id) on delete cascade,
  user_id integer not null references profiles (id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  joined_at timestamptz not null default now(),
  muted smallint not null default 0,
  primary key (group_id, user_id)
);

-- A post shared into a group. Members who joined before this row was created can see the post.
create table if not exists group_posts (
  id integer generated by default as identity primary key,
  group_id integer not null references line_groups (id) on delete cascade,
  post_id integer not null references posts (id) on delete cascade,
  shared_by integer not null references profiles (id) on delete cascade,
  note text,
  created_at timestamptz not null default now(),
  unique (group_id, post_id)
);

-- Comments with a group_id belong to that group's private thread on the post.
alter table comments add column if not exists group_id integer references line_groups (id) on delete cascade;
alter table notifications add column if not exists group_id integer references line_groups (id) on delete cascade;

create index if not exists idx_group_members_user on line_group_members (user_id);
create index if not exists idx_group_posts_group on group_posts (group_id, created_at desc);
create index if not exists idx_group_posts_post on group_posts (post_id);
create index if not exists idx_comments_group on comments (post_id, group_id);

alter table line_groups enable row level security;
alter table line_group_members enable row level security;
alter table group_posts enable row level security;
revoke all on table line_groups from anon, authenticated;
revoke all on table line_group_members from anon, authenticated;
revoke all on table group_posts from anon, authenticated;
